### ISSUE TITLE
Throwing errors after applying lure to fishing pole (crafty.lua:596: bad argument #1 to `strupper)

### ISSUE THREAD

**Issue by yutsuku** [shirsig/crafty#1]
While fishing I noticed that there is some kind of issue **after** applying lure to fishing pole ([Bright Baubles](https://vanilla-twinhead.twinstar.cz/?item=6532) to [Arcanite Fishing Pole](https://vanilla-twinhead.twinstar.cz/?item=19970)  to be exact)

```
Interface\AddOns\crafty\crafty.lua:596: bad argument #1 to `strupper` (string expected, got nil)
```

This error occurs when:
- opening skills window, followed by opening any tab from this window (character, reputation, honor)
- player auras state changes

**Comment by shirsig** [comment]
Hey, thanks for reporting. Could you try if it still happens in the newest version?

**Comment by yutsuku** [comment]
Now it throws this instead

```
Interface\AddOns\crafty\crafty.lua:492: table index is nil
```

**Comment by shirsig** [comment]
Ok, hopefully now it'll work :)

**Comment by yutsuku** [comment]
No errors this time. Cheers!

**Comment by shirsig** [comment]
Great :)
