### ISSUE TITLE
random pop up

### ISSUE THREAD

**Issue by waytoomuchgaming** [shirsig/crafty#3]
https://imgur.com/J1fo6ua

**Comment by shirsig** [comment]
couldn't reproduce it but changed something I thought might have caused it ...

**Comment by waytoomuchgaming** [comment]
Could not reproduce it either. It seem to be very random (it appeared around 10 times in a month, where it started to upset me enough to open a bug report ^^).
I'll install the next version.

**Comment by shirsig** [comment]
Oh, you must've had a very old version then? Thought it would've been caused by the recent update. Maybe it was fixed a while ago already.

**Comment by waytoomuchgaming** [comment]
No, i allways make sure to use the latest version of an addon before reporting a bug (but on that one, you made an update a couple hours ago before i opened the issue - which have not reappered, so far, after i used the very last version).
